// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDD_OLS
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Добавить элемент в список")]
    public partial class ДобавитьЭлементВСписокFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Insert_Node_in_List.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "Добавить элемент в список", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Добавить элемент в голову списка")]
        [NUnit.Framework.CategoryAttribute("позитивный")]
        public virtual void ДобавитьЭлементВГоловуСписка()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Добавить элемент в голову списка", new string[] {
                        "позитивный"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("я инициализирую список", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Допустим ");
#line 6
 testRunner.And("добавляю в него элементы", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 7
 testRunner.When("я добавляю элемент в голову списка", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 8
 testRunner.Then("в голове списка будет добавленный элемент", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Добавить элемент в хвост списка")]
        [NUnit.Framework.CategoryAttribute("позитивный")]
        public virtual void ДобавитьЭлементВХвостСписка()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Добавить элемент в хвост списка", new string[] {
                        "позитивный"});
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("я инициализирую список", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Допустим ");
#line 13
 testRunner.And("добавляю в него элементы", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 14
 testRunner.When("я добавляю элемент в хвост списка", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 15
 testRunner.Then("в хвосте списка будет добавленный элемент", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Добавить элемент после заданного узла")]
        [NUnit.Framework.CategoryAttribute("позитивный")]
        public virtual void ДобавитьЭлементПослеЗаданногоУзла()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Добавить элемент после заданного узла", new string[] {
                        "позитивный"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("я инициализирую список", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Допустим ");
#line 20
 testRunner.And("добавляю в него элементы", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 21
 testRunner.When("я добавляю элемент в список после заданного узла", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 22
 testRunner.Then("после зданного узла будет добавленный элемент", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
