// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDD_OLS
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Удалить Узел или Список")]
    public partial class УдалитьУзелИлиСписокFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Remove_Node.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "Удалить Узел или Список", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Удалить заданный узел")]
        [NUnit.Framework.CategoryAttribute("позитивный")]
        public virtual void УдалитьЗаданныйУзел()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Удалить заданный узел", new string[] {
                        "позитивный"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("инициализирую список", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Допустим ");
#line 6
 testRunner.And("я добавляю в него элементы", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 7
 testRunner.When("удаляю заданный узел", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 8
 testRunner.Then("данный узел удален", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Удалить список")]
        [NUnit.Framework.CategoryAttribute("позитивный")]
        public virtual void УдалитьСписок()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Удалить список", new string[] {
                        "позитивный"});
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("инициализирую список", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Допустим ");
#line 13
 testRunner.And("я добавляю в него элементы", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 14
 testRunner.When("удаляю список", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 15
 testRunner.Then("список удален", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
